### ISSUE TITLE
Playing yourself is possible

### ISSUE THREAD

**Issue by ChipBeach** [corya14/tic-tactical-toe#10]
But it ends quickly, and at least I won:

<img width="468" alt="Screen Shot 2021-04-30 at 7 58 05 PM" src="https://user-images.githubusercontent.com/81936020/116764323-c194d800-a9ee-11eb-80a6-2a822f0c03e8.png">

Not sure how I got in this state, but we should protect against.

**Comment by corya14** [comment]
This must've been introduced in 1b1418eea23cb78a5af77313d283fe6c0602bb4a.
