### ISSUE TITLE
Name of board owner should be displayed

### ISSUE THREAD

**Issue by ChipBeach** [corya14/tic-tactical-toe#11]
If its possible to put the boarder owners name on their board that would be great.  Generally speaking its not necessary because if you start a game you'll know its "your" board so the name is redundant.  However, when you're playing both boards its very easy to mix them up.  Then you play out of turn on one when you should be playing on the other.  Then you spend time trying to figure why the page is not responding anymore.

**Comment by corya14** [comment]
@ChipBeach board creator is always the username at the bottom and the current turn is indicated by a yellow bgcolor. It sounds like you want the name of the current logged in user to display.
