### ISSUE TITLE
Game socket closing unexpectedly in docker build

### ISSUE THREAD

**Issue by corya14** [corya14/tic-tactical-toe#4]
Can't reproduce reliably yet.

**Comment by corya14** [comment]
If "# of tacs" is empty the unexpected close occurs.   Note: reload of page resets the connection.

@ChipBeach I wasn't able to reproduce this. It looks to be fine as of 3d008c14b1f6e342249fb7764270123543bd4013.

![image](https://user-images.githubusercontent.com/7156047/116719122-b5862780-a9a8-11eb-9ad9-8e27a08f2430.png)

**Comment by corya14** [comment]
![image](https://user-images.githubusercontent.com/7156047/116722933-06981a80-a9ad-11eb-86b4-fc58f673614c.png)

**Comment by ChipBeach** [comment]
Another scenario.  Note: d4 attacking d3.  What is unique is that both cells have 2 tacs.  1 tac to be used in the attack.  Causes the unexpected socket closure.


<img width="299" alt="Screen Shot 2021-04-30 at 10 44 46 PM" src="https://user-images.githubusercontent.com/81936020/116768600-ad100a00-aa05-11eb-8771-3415c2f62205.png">

**Comment by corya14** [comment]
Bug occurs when there are more defenders than attackers here:
```
for i in range(0, len(defender_d6)):
      if attacker_d6[i] > defender_d6[i]:
         defending -= 1
         def_loss += 1
         if defending == 0:
            break
      else:
         attacking -= 1
         atk_loss += 1
```

**Comment by corya14** [comment]
Good find! I need to figure out how to use the testing framework.
