### ISSUE TITLE
Attacker retains turn after an attack

### ISSUE THREAD

**Issue by ChipBeach** [corya14/tic-tactical-toe#7]
Until an attacker wins a cell or runs out of tacs the turn continues to be theirs

**Comment by corya14** [comment]
@ChipBeach I made this on purpose, sorry I should have let you know! Turns only end if someone acquires a new square or performs an idle/internal move. This lets attackers "roll dice" and view outcomes as they attack and is similar to risk.

**Comment by ChipBeach** [comment]
Okay no problem.  I'll add that to the rules.

> @ChipBeach I made this on purpose, sorry I should have let you know! Turns only end if someone acquires a new square or performs an idle/internal move. This lets attackers "roll dice" and view outcomes as they attack and is similar to risk.
