### ISSUE TITLE
In an IDLE move tacs specified can matter

### ISSUE THREAD

**Issue by ChipBeach** [corya14/tic-tactical-toe#9]
For an IDLE move where you are just amassing tacs if you have more tacs specified than are in the cell it will consider it an invalid move.  Ideally it shouldn't care how many you specify or if you specify any, although not specifying leads to the unexpected disconnect.

**Comment by corya14** [comment]
Disconnect on no input sounds like a bug. I will double check the number of tacs constraints and try and eliminate the constraint for IDLE.

**Comment by corya14** [comment]
I have a fix that allows moves with no tacs specified or 0 tacs and ignores tac quantity constraints. However, attempting to move >9 tacs even for IDLE will fail the regex.
